CREATE TABLE IF NOT EXISTS USERS (
    fname VARCHAR(250) NOT NULL,
    lname VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL PRIMARY KEY,
    pass VARCHAR(250) NOT NULL,
    address VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS CAREGIVER (
    email VARCHAR(250) NOT NULL PRIMARY KEY,
    cg1 VARCHAR(250) ,
    cg2 VARCHAR(250)
);
CREATE TABLE IF NOT EXISTS CGDETAILS (
    email VARCHAR(250) NOT NULL PRIMARY KEY,
    status VARCHAR(250)
);